### ISSUE TITLE
Possible to kill @docker handler

### ISSUE THREAD

**Issue by dandare100** [evilsocket/medusa#2]
In some cases (depending on the setup) it is possible to kill the jail docker container with

```
kill 1

```
as the command.

This would kill the init parent process in the container and stop the container. 
The honeypot  would then return errors instead of delegating to the running container for commands that are not already cached.

This could probably be prevented on the docker/host side by having the container always restart or having different users for starting and running the exec. 

Maybe a configurable blacklist of commands that wont be sent to the container.
I know it's not the core of the project, and need not be changed. :-)  I am just mentioning it.

**Comment by evilsocket** [comment]
this is more a docker configuration related thing i believe, it's up to everyone configuring the jail as they please, including auto restart ... i don't know how a blacklist of commands would work, i'm sure there would be tons of ways to bypass it.

also on my setup, kill 1 just doesn't kill the container

    docker container create --name medusajail busybox tail -f /dev/null

**Comment by dandare100** [comment]
Agreed with it being a config related thing.

Did you check if the container was running after kill 1 by 

```
docker ps
```
or by retyping command.
I got caught out by retyping a previous command but it returned a cached command so I thought the container was still up but it wasn't

Thanks for the replies.

**Comment by evilsocket** [comment]
![Schermata da 2021-08-28 20-28-11](https://user-images.githubusercontent.com/86922/131227393-b6601b91-44e9-4628-a5a8-c9019f2e8d1c.png)

yep, alive and well ... maybe it depends on the local configuration? what image are you using?

**Comment by dandare100** [comment]
Interesting. I used the nginx image and it kills fine.
Yours is the busy box.

I suspect it is because of the signal traps and the shells that differ. nginx has a dash shell.

sh for busybox image catches no signals
```
/ # cat /proc/1/status | grep Sig
SigQ:	0/62625
SigPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000000000
SigCgt:	0000000000000000
```

sh for nginx image catches 198016a07 which has bit 15 set in the mask which is SIGTERM
```
root@3241daa3c6aa:/docker-entrypoint.d# cat /proc/1/status | grep Sig
SigQ:	0/62625
SigPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000040001000
SigCgt:	0000000198016a07
```

TIL, thanks

**Comment by evilsocket** [comment]
ah! good catch :D i've changed the README to refer to the busybox image, also linked other images that can be useful to simulate Ciscos and others 👍🏻
