### ISSUE TITLE
Cannot specify LF at the end of SSH server_id

### ISSUE THREAD

**Issue by BeanBagKing** [evilsocket/medusa#3]
This may be something I'm just doing wrong. I was playing with impersonating services, nothing specific, but I wanted it to look "real", so I grabbed some banners from /usr/share/nmap/nmap-service-probes. Setting SSH server_id to something expecting a \r\n ending works fine. However, a server_id ending in \n  cannot be set:

### Working Example

From the service probes file I can find this:
```
match ssh m|^SSH-([\d.]+)-PSFTPd\. Secure FTP Server ready\r\n| p/PSFTPd/ i/protocol $1/ o/Windows/ cpe:/a:pleis:psftpd/ cpe:/o:microsoft:windows/a
```
And set my server_id to this:
```
SSH-2.3-PSFTPd. Secure FTP Server ready
```
and Nmap correctly identifies the service as:
```
PORT     STATE SERVICE REASON         VERSION
2222/tcp open  ssh     syn-ack ttl 63 PSFTPd (protocol 2.3)
Service Info: OS: Windows; CPE: cpe:/o:microsoft:windows
```

### Non-working example

However, if I try something like this:
```
match ssh m|^SSH-([\d.]+)-TECHNICOLOR_SW_([\d.]+)\n| p/Technicolor SA sshd/ v/$2/ i/protocol $1/ d/broadband router/
```
And set my server_id to:
```
SSH-1.99-TECHNICOLOR_SW_2.0
```
I get back:
```
1 service unrecognized despite returning data. If you know the service/version, please submit the following fingerprint at https://nmap.org/cgi-bin/submit.cgi?new-service :
SF-Port2222-TCP:V=7.91%I=7%D=8/29%Time=612B8DBD%P=x86_64-pc-linux-gnu%r(NU
SF:LL,1D,"SSH-1\.99-TECHNICOLOR_SW_2\.0\r\n");
```
As near as I can tell that should match except for the ending, I've tried numerous variations though. It seems the problem is Nmap wasn't expecting the carriage return preceding the line feed, e.g the "\r\n" on the last line that wasn't specified by the user.

If I insert a new line between the end of the string (2.0) and the last single tick ('), this seems to get interpreted in Nmap as \x20 (space?). If I look at this in a hex editor though, it appears to be the correct CR character (0A). Trying to manually insert a CR in vim (e.g. CTRL+V 10) seems to insert a 00 (null) character, and result in the error below (no surprise)

```
bbk@ubuntu:~/medusa$ ./medusa 
thread 'main' panicked at 'error parsing service file: Scan(ScanError { mark: Marker { index: 46, line: 3, col: 11 }, info: "while scanning a quoted scalar, found unexpected end of stream" })', src/main.rs:83:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I might be doing something wrong, I'm going between various escape characters and ascii tables in ocatal/dec/hex but there doesn't appear to be a way to force a CR only at the end of the server_id string, and without being able to do that, it seems some server banners are going to be impossible to impersonate.

**Comment by evilsocket** [comment]
~~i think the issue here is that the server_id field gets trimmed and then `\r\n` is added by default ... i guess i'll just remove the trim and let the users decide their strategy :D~~

forget what i said, i just checked and there's no trimming going on ... i'll investigate this and fix, thanks for reporting

**Comment by evilsocket** [comment]
this works great :D 

```server_id: "SSH-1.99-TECHNICOLOR_SW_2.0\n"```

gives

```PORT     STATE SERVICE REASON         VERSION
2222/tcp open  ssh     syn-ack ttl 64 Technicolor SA sshd 2.0 (protocol 1.99)```

**Comment by BeanBagKing** [comment]
Thank you, it looks like nothing was changed, it was just the difference between ' and " at the end?

For anyone coming behind me. Note the ' enclosing the server_id in the readme example, vs the " used above. Using a ' treats the \n as a literal which Nmap parses as an unfound protocol (note the \\\n below):

> SSH-1\.99-TECHNICOLOR_SW_2\.0\\\n\r\n

### Edit
This might have created another problem. When using " in the server_id, and trying to connect to ssh from another host, I get:

```
# ssh 192.168.0.129 -p 2222
Bad packet length 218759168.
ssh_dispatch_run_fatal: Connection to 192.168.0.129 port 2222: message authentication code incorrect
```

### Edit 2
Other combinations (e.g. '"banner"' or "'banner'") result in:
```
# ssh 192.168.0.129 -p 2222
kex_exchange_identification: banner line contains invalid characters
banner exchange: Connection to 192.168.0.129 port 2222: invalid format
```

**Comment by evilsocket** [comment]
yes, if you want escape sequences to be correctly parsed from YAML you have to use double quotes

**Comment by evilsocket** [comment]
if you need to use double quotes in the server_id:

```yaml
server_id: "some\"thing"
```

**Comment by evilsocket** [comment]
http://blogs.perl.org/users/tinita/2018/03/strings-in-yaml---to-quote-or-not-to-quote.html

**Comment by BeanBagKing** [comment]
I don't necessarily want to use double quotes, I was just trying to find a way to satisfy both the Nmap scan and the ssh connection. Sorry if I'm missing something obvious that you're saying. Here's what I get when using single quotes vs double.

Using this `server_id: "SSH-1.99-TECHNICOLOR_SW_2.0\n"` satisfies Nmap, it detects the TECHNICOLOR banner correctly. However, when trying to connect to the honeyservice via SSH, I get the `Bad packet length 218759168.` message.

Using `server_id: 'SSH-1.99-TECHNICOLOR_SW_2.0\n'`, I get an unknown banner in Nmap, however, SSH connects just fine and presents me with the expected # prompt.

Examples:
```
With single quotes

┌──(root@system)-[/]
└─# nmap -sV --open --reason 192.168.0.129
Starting Nmap 7.91 ( https://nmap.org ) at 2021-08-29 12:51 EDT
Nmap scan report for 192.168.0.129
Host is up, received reset ttl 63 (0.0012s latency).
Not shown: 999 closed ports
Reason: 999 resets
PORT     STATE SERVICE REASON         VERSION
2222/tcp open  ssh     syn-ack ttl 63 (protocol 1.99)
1 service unrecognized despite returning data. If you know the service/version, please submit the following fingerprint at https://nmap.org/cgi-bin/submit.cgi?new-service :
SF-Port2222-TCP:V=7.91%I=7%D=8/29%Time=612BBB2D%P=x86_64-pc-linux-gnu%r(NU
SF:LL,1F,"SSH-1\.99-TECHNICOLOR_SW_2\.0\\n\r\n");

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 7.63 seconds

┌──(root@system)-[/]
└─# ssh 192.168.0.129 -p 2222
# whoami
sh: command not found: "whoami"
# exit
Connection to 192.168.0.129 closed.
```

```
With double quotes

┌──(root@system)-[/]
└─# nmap -sV --open --reason 192.168.0.129
Starting Nmap 7.91 ( https://nmap.org ) at 2021-08-29 12:52 EDT
Nmap scan report for 192.168.0.129
Host is up, received echo-reply ttl 63 (0.0012s latency).
Not shown: 999 closed ports
Reason: 999 resets
PORT     STATE SERVICE REASON         VERSION
2222/tcp open  ssh     syn-ack ttl 63 Technicolor SA sshd 2.0 (protocol 1.99)
Service Info: Device: broadband router

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 1.59 seconds

┌──(root@system)-[/]
└─# ssh 192.168.0.129 -p 2222
Bad packet length 218759168.
ssh_dispatch_run_fatal: Connection to 192.168.0.129 port 2222: message authentication code incorrect
```

**Comment by evilsocket** [comment]
oooo i see!! i only tried nmap, but didn't check the ssh connection itself, i need to investigate this

**Comment by evilsocket** [comment]
So, this is due to `thrussh`, a crate i'm using to create a SSH server. The two termination bytes after the server_id are hardcoded as `\r\n`, so prepending a `\n` via server_id string will break the protocol. I'm trying to reach the author in order to allow the library to configure a custom terminator for the server id. The project is not on github ( https://nest.pijul.com/pijul/thrussh ) and there's a bug in the registration process of that platform. I'm trying to contact the author.

![Schermata da 2021-08-31 13-21-46](https://user-images.githubusercontent.com/86922/131494364-13f008af-4994-4c93-aa98-6e27337cccc1.png)

**Comment by evilsocket** [comment]
the issue is tracked here https://nest.pijul.com/pijul/thrussh/discussions/51

**Comment by evilsocket** [comment]
I'm sorry if it took so long, the original ssh crate was pretty much abandoned but recently I found a well maintained fork and submitted a PR to address this.

You can now specify a server id which includes non standard line terminators via the server_id_raw configuration directive:

```yaml
proto: ssh
address: '127.0.0.1:2222'
server_id_raw: "SSH-1.99-TECHNICOLOR_SW_2.0\n"
banner: 'Last login: Mon Sep  5 14:12:09 2022 from 127.0.0.1'
prompt: '# '
key: '/tmp/example-ssh.key'
timeout: 15
commands:
  - parser: '^exit(\s.+)?$'
    handler: '@exit'
```
