### ISSUE TITLE
private key incorrect format

### ISSUE THREAD

**Issue by kylegbakker** [evilsocket/medusa#4]
Good morning,

So I have recently been attempting to configure the medusa honeypot for research and fun purposes and I ran into one particulary annoying issue getting the https protocol to function correctly.

It would appear that `rustls::pemfile::rsa_private_keys` requires the private key to be in PKCS#1 format, however the cert/key generation step in the readme `openssl req -newkey rsa:2048 -nodes -keyout medusa-https.key -x509 -days 365 -out medusa-https.crt` generates a private key in PKCS#8 format, which causes rust to panic and die when running medusa. Not sure if this is an issue with openssl version difference maybe? I'm using `OpenSSL 1.1.1`

This was remediated by adding `RSA` to the header in the key file.

Before:
`-----BEGIN PRIVATE KEY-----`
After:
`-----BEGIN RSA PRIVATE KEY-----`

Also I noticed that the certificate path in `http/config.rs` has the cert file as `medusa-https.cert` whereas the command in the readme generates `medusa-https.crt` which tripped me up for longer than I would care to admit ha ha ha.

Kind regards,
Kyle.

**Comment by evilsocket** [comment]
Hi Kyle! 

LOL I manually added the RSA string to fix like you did and forgot to implement an automated fix for it, thanks for reminding me! :D

Will fix both asap.

**Comment by kylegbakker** [comment]
Ha ha ha I did wonder that if i'm being perfectly honest. Happy to have helped :)

**Comment by evilsocket** [comment]
it should be able to load both PKCS#1 and PKCS#8 now 👍🏻
